apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: dimtoolui
  namespace: {{ .Values.namespace }}
  annotations:
    kubernetes.io/ingress.class: alb
    #alb.ingress.kubernetes.io/target-type: ip
spec:
  rules:
  - host: "dimtoolui-{{ .Values.namespace }}.{{ .Values.route_subdomain }}"
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: dimtoolui
            port:
              number: {{ .Values.service.port }}
